### ISSUE TITLE
"show unusabled cards", what is it?

### ISSUE THREAD

**Issue by stopfstedt** [Alsciende/thronesdb#237]
![selection_220](https://user-images.githubusercontent.com/1410427/49825917-73f27480-fd3a-11e8-8aeb-f25eb051551f.png)

- [x] figure out what this does (clicking around didn't do anything for me), if anything.
- [ ] fix label, _unusabled_ is not a proper English word. ~or remove this altogether (see step 1).~

**Comment by ystros** [comment]
By default, cards you cannot be put in your deck aren't displayed on the deck builder. For example, this Greyjoy Banner Lion deck hides any loyal Lannister cards because you're not allowed to put them in your deck.

![screen shot 2018-12-11 at 12 03 19 pm](https://user-images.githubusercontent.com/145077/49826969-072ca980-fd3d-11e8-869b-20e8723ef861.png)

Turn the option on, and it will show you those cards (note Cersei Lannister is now listed):

![screen shot 2018-12-11 at 12 03 36 pm](https://user-images.githubusercontent.com/145077/49827064-44913700-fd3d-11e8-8b31-afa651c93621.png)

This applies to any deck building restrictions, Banners are just a quick example. You can also quickly see what it does by going to a faction not allowed by your deck, then turning on the option.

I feel the main use case is if I want a particular card in my deck that my current faction / agenda won't allow. It allows you to see and add those cards, then adjust your faction and agenda as necessary to allow you to use it. It's also probably useful for something like the Conclave agenda, where you may know which Maesters across all factions you want but not necessarily what you want as your primary faction.

Renaming for grammar and clarity would be good, though.
